blank_issues_enabled: true
contact_links:
  - name: 💬 Question or discussion
    url: https://github.com/alexeikaratai/smartdock/discussions
    about: For usage questions and ideas that aren't a bug report yet.
